#!/usr/bin/env bash
# java.sh — Java/Maven OSS repo catalog
#
# Provides: JAVA_REPOS array  (sourced by master.sh)
# Format per entry: "<clone-url>  <category>  <dir-name>"
#
# Categories:
#   spring-demo   spring-prod   spring-cloud
#   java-large    java-medium   java-infra
#   java-data     java-tools    java-android
#   java-security java-sast
# ─────────────────────────────────────────────────────────────────────────────
[[ -n "${_JAVA_SH_LOADED:-}" ]] && return 0
_JAVA_SH_LOADED=1

JAVA_REPOS=(

  # ── spring-demo ─────────────────────────────────────────────────────────────
  "https://github.com/spring-projects/spring-petclinic.git                        spring-demo       spring-petclinic"
  "https://github.com/spring-petclinic/spring-petclinic-microservices.git         spring-demo       spring-petclinic-microservices"
  "https://github.com/jhipster/jhipster-sample-app.git                            spring-demo       jhipster-sample-app"
  "https://github.com/spring-projects/spring-mvc-showcase.git                     spring-demo       spring-mvc-showcase"
  "https://github.com/spring-projects/spring-data-examples.git                    spring-demo       spring-data-examples"
  "https://github.com/spring-attic/greenhouse.git                                 spring-demo       greenhouse"
  "https://github.com/spring-projects/spring-boot.git                             spring-demo       spring-boot"
  "https://github.com/spring-projects/spring-framework.git                        spring-demo       spring-framework"
  "https://github.com/spring-projects/spring-security.git                         spring-demo       spring-security"
  "https://github.com/spring-projects/spring-authorization-server.git             spring-demo       spring-authorization-server"
  "https://github.com/spring-projects/spring-batch.git                            spring-demo       spring-batch"
  "https://github.com/spring-projects/spring-integration.git                      spring-demo       spring-integration"

  # ── spring-prod ─────────────────────────────────────────────────────────────
  "https://github.com/macrozheng/mall.git                                         spring-prod       mall"
  "https://github.com/apolloconfig/apollo.git                                      spring-prod       apollo"
  "https://github.com/alibaba/nacos.git                                            spring-prod       nacos"
  "https://github.com/alibaba/Sentinel.git                                         spring-prod       sentinel"
  "https://github.com/apache/shardingsphere.git                                    spring-prod       shardingsphere"
  "https://github.com/dromara/Sa-Token.git                                         spring-prod       sa-token"
  "https://github.com/halo-dev/halo.git                                            spring-prod       halo"
  "https://github.com/elunez/eladmin.git                                           spring-prod       eladmin"
  "https://github.com/jeecgboot/JeecgBoot.git                                      spring-prod       jeecgboot"
  "https://github.com/macrozheng/mall-swarm.git                                    spring-prod       mall-swarm"
  "https://github.com/YunaiV/ruoyi-vue-pro.git                                     spring-prod       ruoyi-vue-pro"
  "https://github.com/dromara/RuoYi-Vue-Plus.git                                   spring-prod       ruoyi-vue-plus"
  "https://github.com/xkcoding/spring-boot-demo.git                                spring-prod       spring-boot-demo"
  "https://github.com/hs-web/hsweb-framework.git                                   spring-prod       hsweb-framework"
  "https://github.com/doocs/advanced-java.git                                       spring-prod       advanced-java"
  "https://github.com/guchengwuyue/yshopmall.git                                    spring-prod       yshopmall"
  "https://github.com/cloudfavorites/favorites-web.git                              spring-prod       favorites-web"
  "https://github.com/lenve/vhr.git                                                 spring-prod       vhr"
  "https://github.com/lihengming/spring-boot-api-project-seed.git                  spring-prod       api-project-seed"

  # ── spring-cloud ────────────────────────────────────────────────────────────
  "https://github.com/alibaba/spring-cloud-alibaba.git                             spring-cloud      spring-cloud-alibaba"
  "https://github.com/spring-cloud/spring-cloud-gateway.git                        spring-cloud      spring-cloud-gateway"
  "https://github.com/spring-cloud/spring-cloud-config.git                         spring-cloud      spring-cloud-config"
  "https://github.com/spring-cloud/spring-cloud-netflix.git                        spring-cloud      spring-cloud-netflix"
  "https://github.com/spring-cloud/spring-cloud-openfeign.git                      spring-cloud      spring-cloud-openfeign"
  "https://github.com/spring-cloud/spring-cloud-sleuth.git                         spring-cloud      spring-cloud-sleuth"
  "https://github.com/pig-mesh/pig.git                                              spring-cloud      pig"
  "https://github.com/sqshq/piggymetrics.git                                        spring-cloud      piggymetrics"
  "https://github.com/zhoutaoo/SpringCloud.git                                      spring-cloud      springcloud-learning"
  "https://github.com/forezp/SpringCloudLearning.git                               spring-cloud      springcloudlearning"
  "https://github.com/yinjihuan/spring-cloud.git                                    spring-cloud      yinjihuan-cloud"
  "https://github.com/liuweijw/fw-cloud-framework.git                               spring-cloud      fw-cloud-framework"
  "https://github.com/itmuch/spring-cloud-docker-microservice-book-code.git         spring-cloud      cloud-docker-book"

  # ── java-large ──────────────────────────────────────────────────────────────
  "https://github.com/apache/kafka.git                                              java-large        kafka"
  "https://github.com/elastic/elasticsearch.git                                     java-large        elasticsearch"
  "https://github.com/opensearch-project/OpenSearch.git                             java-large        opensearch"
  "https://github.com/apache/cassandra.git                                          java-large        cassandra"
  "https://github.com/jenkinsci/jenkins.git                                         java-large        jenkins"
  "https://github.com/apache/druid.git                                              java-large        druid"
  "https://github.com/apache/pulsar.git                                             java-large        pulsar"
  "https://github.com/apache/flink.git                                              java-large        flink"
  "https://github.com/trinodb/trino.git                                             java-large        trino"
  "https://github.com/keycloak/keycloak.git                                         java-large        keycloak"
  "https://github.com/apache/hadoop.git                                             java-large        hadoop"
  "https://github.com/apache/spark.git                                              java-large        spark"
  "https://github.com/apache/hbase.git                                              java-large        hbase"
  "https://github.com/apache/hive.git                                               java-large        hive"
  "https://github.com/apache/zookeeper.git                                          java-large        zookeeper"
  "https://github.com/apache/tomcat.git                                             java-large        tomcat"
  "https://github.com/eclipse-vertx/vert.x.git                                      java-large        vertx"
  "https://github.com/netty/netty.git                                               java-large        netty"
  "https://github.com/google/guava.git                                              java-large        guava"
  "https://github.com/ReactiveX/RxJava.git                                          java-large        rxjava"
  "https://github.com/apache/dubbo.git                                              java-large        dubbo"
  "https://github.com/grpc/grpc-java.git                                            java-large        grpc-java"
  "https://github.com/square/okhttp.git                                             java-large        okhttp"
  "https://github.com/apache/beam.git                                               java-large        beam"
  "https://github.com/prestodb/presto.git                                           java-large        presto"
  "https://github.com/apache/rocketmq.git                                           java-large        rocketmq"
  "https://github.com/wildfly/wildfly.git                                           java-large        wildfly"
  "https://github.com/eclipse/jetty.project.git                                     java-large        jetty"
  "https://github.com/OpenAPITools/openapi-generator.git                            java-large        openapi-generator"
  "https://github.com/apache/solr.git                                               java-large        solr"
  "https://github.com/apache/nifi.git                                               java-large        nifi"
  "https://github.com/apache/camel.git                                              java-large        camel"
  "https://github.com/hazelcast/hazelcast.git                                       java-large        hazelcast"
  "https://github.com/ignite-grid/ignite.git                                        java-large        ignite"
  "https://github.com/apache/ignite.git                                             java-large        apache-ignite"
  "https://github.com/eclipse/che.git                                               java-large        che"

  # ── java-infra ──────────────────────────────────────────────────────────────
  "https://github.com/redisson/redisson.git                                         java-infra        redisson"
  "https://github.com/lettuce-io/lettuce-core.git                                   java-infra        lettuce"
  "https://github.com/ben-manes/caffeine.git                                        java-infra        caffeine"
  "https://github.com/resilience4j/resilience4j.git                                 java-infra        resilience4j"
  "https://github.com/Netflix/Hystrix.git                                           java-infra        hystrix"
  "https://github.com/Netflix/eureka.git                                            java-infra        eureka"
  "https://github.com/Netflix/ribbon.git                                            java-infra        ribbon"
  "https://github.com/OpenFeign/feign.git                                           java-infra        feign"
  "https://github.com/eclipse/microprofile.git                                      java-infra        microprofile"
  "https://github.com/quarkusio/quarkus.git                                         java-infra        quarkus"
  "https://github.com/micronaut-projects/micronaut-core.git                         java-infra        micronaut"
  "https://github.com/helidon-io/helidon.git                                        java-infra        helidon"
  "https://github.com/undertow-io/undertow.git                                      java-infra        undertow"
  "https://github.com/asynchttpclient/async-http-client.git                         java-infra        async-http-client"
  "https://github.com/apache/activemq.git                                           java-infra        activemq"
  "https://github.com/apache/activemq-artemis.git                                   java-infra        activemq-artemis"
  "https://github.com/zeromq/jeromq.git                                             java-infra        jeromq"
  "https://github.com/google/tink.git                                               java-infra        tink"
  "https://github.com/conscrypt/conscrypt.git                                       java-infra        conscrypt"
  "https://github.com/Netflix/zuul.git                                              java-infra        zuul"
  "https://github.com/micrometer-metrics/micrometer.git                             java-infra        micrometer"
  "https://github.com/open-telemetry/opentelemetry-java.git                         java-infra        opentelemetry-java"
  "https://github.com/openzipkin/zipkin.git                                         java-infra        zipkin"
  "https://github.com/open-telemetry/opentelemetry-java-instrumentation.git         java-infra        otel-java-instrumentation"
  "https://github.com/apache/skywalking.git                                         java-infra        skywalking"
  "https://github.com/pinpoint-apm/pinpoint.git                                     java-infra        pinpoint"

  # ── java-data ───────────────────────────────────────────────────────────────
  "https://github.com/mybatis/mybatis-3.git                                         java-data         mybatis"
  "https://github.com/baomidou/mybatis-plus.git                                     java-data         mybatis-plus"
  "https://github.com/hibernate/hibernate-orm.git                                   java-data         hibernate"
  "https://github.com/jOOQ/jOOQ.git                                                 java-data         jooq"
  "https://github.com/openjpa/openjpa.git                                           java-data         openjpa"
  "https://github.com/liquibase/liquibase.git                                       java-data         liquibase"
  "https://github.com/flyway/flyway.git                                             java-data         flyway"
  "https://github.com/FasterXML/jackson-databind.git                                java-data         jackson-databind"
  "https://github.com/FasterXML/jackson-core.git                                    java-data         jackson-core"
  "https://github.com/FasterXML/jackson-modules-java8.git                           java-data         jackson-modules-java8"
  "https://github.com/google/gson.git                                               java-data         gson"
  "https://github.com/apache/avro.git                                               java-data         avro"
  "https://github.com/apache/parquet-mr.git                                         java-data         parquet"
  "https://github.com/protocolbuffers/protobuf.git                                  java-data         protobuf"
  "https://github.com/apache/lucene.git                                             java-data         lucene"
  "https://github.com/h2database/h2database.git                                     java-data         h2database"
  "https://github.com/pgjdbc/pgjdbc.git                                             java-data         pgjdbc"
  "https://github.com/mysql/mysql-connector-j.git                                   java-data         mysql-connector"
  "https://github.com/brettwooldridge/HikariCP.git                                  java-data         hikaricp"
  "https://github.com/apache/calcite.git                                            java-data         calcite"
  "https://github.com/questdb/questdb.git                                           java-data         questdb"
  "https://github.com/eclipse/jnosql.git                                            java-data         jnosql"
  "https://github.com/orientechnologies/orientdb.git                                java-data         orientdb"
  "https://github.com/neo4j/neo4j.git                                               java-data         neo4j"
  "https://github.com/apache/hbase.git                                              java-data         hbase-data"

  # ── java-tools ──────────────────────────────────────────────────────────────
  "https://github.com/checkstyle/checkstyle.git                                     java-tools        checkstyle"
  "https://github.com/pmd/pmd.git                                                   java-tools        pmd"
  "https://github.com/spotbugs/spotbugs.git                                         java-tools        spotbugs"
  "https://github.com/jacoco/jacoco.git                                             java-tools        jacoco"
  "https://github.com/junit-team/junit5.git                                         java-tools        junit5"
  "https://github.com/mockito/mockito.git                                           java-tools        mockito"
  "https://github.com/assertj/assertj-core.git                                      java-tools        assertj"
  "https://github.com/testcontainers/testcontainers-java.git                        java-tools        testcontainers"
  "https://github.com/google/error-prone.git                                        java-tools        error-prone"
  "https://github.com/typetools/checker-framework.git                               java-tools        checker-framework"
  "https://github.com/javaparser/javaparser.git                                     java-tools        javaparser"
  "https://github.com/jboss-javassist/javassist.git                                 java-tools        javassist"
  "https://github.com/cglib/cglib.git                                               java-tools        cglib"
  "https://github.com/raphw/byte-buddy.git                                          java-tools        byte-buddy"
  "https://github.com/robolectric/robolectric.git                                   java-tools        robolectric"
  "https://github.com/apache/maven.git                                              java-tools        maven"
  "https://github.com/gradle/gradle.git                                             java-tools        gradle"
  "https://github.com/google/auto.git                                               java-tools        google-auto"
  "https://github.com/square/javapoet.git                                           java-tools        javapoet"
  "https://github.com/rzwitserloot/lombok.git                                       java-tools        lombok"
  "https://github.com/mapstruct/mapstruct.git                                       java-tools        mapstruct"
  "https://github.com/immutables/immutables.git                                     java-tools        immutables"
  "https://github.com/pitest/pitest.git                                             java-tools        pitest"
  "https://github.com/archunit/archunit.git                                         java-tools        archunit"
  "https://github.com/diffplug/spotless.git                                         java-tools        spotless"
  "https://github.com/google/google-java-format.git                                 java-tools        google-java-format"
  "https://github.com/spring-projects/sts4.git                                      java-tools        sts4"
  "https://github.com/eclipse/eclipse.jdt.ls.git                                    java-tools        jdt-ls"

  # ── java-android ────────────────────────────────────────────────────────────
  "https://github.com/square/retrofit.git                                           java-android      retrofit"
  "https://github.com/bumptech/glide.git                                            java-android      glide"
  "https://github.com/square/picasso.git                                            java-android      picasso"
  "https://github.com/greenrobot/EventBus.git                                       java-android      eventbus"
  "https://github.com/greenrobot/greenDAO.git                                       java-android      greendao"
  "https://github.com/JakeWharton/butterknife.git                                   java-android      butterknife"
  "https://github.com/ReactiveX/RxAndroid.git                                       java-android      rxandroid"
  "https://github.com/facebook/fresco.git                                           java-android      fresco"
  "https://github.com/airbnb/lottie-android.git                                     java-android      lottie"
  "https://github.com/dagger/dagger.git                                             java-android      dagger"
  "https://github.com/Tencent/tinker.git                                            java-android      tinker"
  "https://github.com/alibaba/ARouter.git                                           java-android      arouter"
  "https://github.com/nostra13/Android-Universal-Image-Loader.git                   java-android      uil"
  "https://github.com/CymChad/BaseRecyclerViewAdapterHelper.git                     java-android      brvah"
  "https://github.com/zhihu/Matisse.git                                             java-android      matisse"
  "https://github.com/square/leakcanary.git                                         java-android      leakcanary"
  "https://github.com/JakeWharton/timber.git                                        java-android      timber"
  "https://github.com/permissions-dispatcher/PermissionsDispatcher.git              java-android      permissions-dispatcher"

  # ── java-security ───────────────────────────────────────────────────────────
  "https://github.com/auth0/java-jwt.git                                            java-security     java-jwt"
  "https://github.com/jwtk/jjwt.git                                                java-security     jjwt"
  "https://github.com/pac4j/pac4j.git                                               java-security     pac4j"
  "https://github.com/bouncycastle/bc-java.git                                      java-security     bc-java"
  "https://github.com/nimbusds/nimbus-jose-jwt.git                                  java-security     nimbus-jose-jwt"
  "https://github.com/google/tink.git                                               java-security     tink-security"
  "https://github.com/shiroproject/shiro.git                                        java-security     shiro"
  "https://github.com/apereo/cas.git                                                java-security     cas"
  "https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server.git         java-security     openid-connect"
  "https://github.com/spring-attic/spring-security-oauth.git                        java-security     spring-security-oauth"
  "https://github.com/zalando/problem.git                                           java-security     zalando-problem"
  "https://github.com/OWASP/java-html-sanitizer.git                                java-security     java-html-sanitizer"
  "https://github.com/spotbugs/spotbugs.git                                         java-security     spotbugs-security"

  # ── java-medium ─────────────────────────────────────────────────────────────
  "https://github.com/zaproxy/zaproxy.git                                           java-medium       zaproxy"
  "https://github.com/google/guice.git                                              java-medium       guice"
  "https://github.com/dropwizard/dropwizard.git                                     java-medium       dropwizard"
  "https://github.com/graphql-java/graphql-java.git                                 java-medium       graphql-java"
  "https://github.com/apache/commons-lang.git                                       java-medium       commons-lang"
  "https://github.com/apache/commons-collections.git                                java-medium       commons-collections"
  "https://github.com/apache/commons-io.git                                         java-medium       commons-io"
  "https://github.com/apache/commons-codec.git                                      java-medium       commons-codec"
  "https://github.com/apache/commons-compress.git                                   java-medium       commons-compress"
  "https://github.com/apache/poi.git                                                java-medium       poi"
  "https://github.com/apache/pdfbox.git                                             java-medium       pdfbox"
  "https://github.com/apache/tika.git                                               java-medium       tika"
  "https://github.com/jhy/jsoup.git                                                 java-medium       jsoup"
  "https://github.com/skylot/jadx.git                                               java-medium       jadx"
  "https://github.com/google/jimfs.git                                              java-medium       jimfs"
  "https://github.com/openstreetmap/osmosis.git                                     java-medium       osmosis"
  "https://github.com/burningwave/core.git                                          java-medium       burningwave"
  "https://github.com/lionsoul2014/ip2region.git                                    java-medium       ip2region"
  "https://github.com/apache/commons-math.git                                       java-medium       commons-math"
  "https://github.com/apache/commons-text.git                                       java-medium       commons-text"
  "https://github.com/apache/commons-csv.git                                        java-medium       commons-csv"
  "https://github.com/apache/commons-net.git                                        java-medium       commons-net"
  "https://github.com/eclipse/eclipse-collections.git                               java-medium       eclipse-collections"
  "https://github.com/vavr-io/vavr.git                                              java-medium       vavr"
  "https://github.com/amaembo/streamex.git                                          java-medium       streamex"

  # ── java-sast (deliberately vulnerable / benchmark apps) ─────────────────────
  "https://github.com/WebGoat/WebGoat.git                                           java-sast         webgoat"
  "https://github.com/OWASP-Benchmark/BenchmarkJava.git                             java-sast         owasp-benchmark"
  "https://github.com/edu-secmachine/javulna.git                                    java-sast         javulna"
  "https://github.com/JoyChou93/java-sec-code.git                                   java-sast         java-sec-code"
  "https://github.com/appsecco/dvja.git                                             java-sast         dvja"
  "https://github.com/CSPF-Founder/JavaVulnerableLab.git                            java-sast         javavulnerablelab"
  "https://github.com/DataDog/vulnerable-java-application.git                       java-sast         vulnado"
  "https://github.com/Checkmarx/Goatlin.git                                         java-sast         goatlin"
  "https://github.com/OWASP/SecurityShepherd.git                                    java-sast         security-shepherd"
  "https://github.com/righettod/poc-xxe.git                                         java-sast         poc-xxe"
  "https://github.com/righettod/poc-graphql.git                                     java-sast         poc-graphql"
  "https://github.com/snoopysecurity/Vulnerable-Code-Snippets.git                   java-sast         vuln-snippets"
  "https://github.com/frohoff/ysoserial.git                                         java-sast         ysoserial"
  "https://github.com/GrrrDog/Java-Deserialization-Cheat-Sheet.git                  java-sast         java-deser-cheatsheet"
  "https://github.com/jaiswalakshansh/Damn-Vulnerable-GraphQL-Application.git       java-sast         dvga-java"
)
