#!/usr/bin/env bash
# java.sh — Java/Maven OSS repo catalog
#
# Provides: JAVA_REPOS array  (sourced by master.sh)
# Format per entry: "<clone-url>  <category>  <dir-name>"
#
# Categories:
#   java      java      java
#   java       java      java
#   java        java       java
#   java    java
# ─────────────────────────────────────────────────────────────────────────────
[[ -n "${_JAVA_SH_LOADED:-}" ]] && return 0
_JAVA_SH_LOADED=1

JAVA_REPOS=(

  # ── java ─────────────────────────────────────────────────────────────
  "https://github.com/spring-projects/spring-petclinic.git                        java          spring-petclinic"
  "https://github.com/spring-petclinic/spring-petclinic-microservices.git         java          spring-petclinic-microservices"
  "https://github.com/jhipster/jhipster-sample-app.git                            java          jhipster-sample-app"
  "https://github.com/spring-projects/spring-mvc-showcase.git                     java          spring-mvc-showcase"
  "https://github.com/spring-projects/spring-data-examples.git                    java          spring-data-examples"
  "https://github.com/spring-attic/greenhouse.git                                 java          greenhouse"
  "https://github.com/spring-projects/spring-boot.git                             java          spring-boot"
  "https://github.com/spring-projects/spring-framework.git                        java          spring-framework"
  "https://github.com/spring-projects/spring-security.git                         java          spring-security"
  "https://github.com/spring-projects/spring-authorization-server.git             java          spring-authorization-server"
  "https://github.com/spring-projects/spring-batch.git                            java          spring-batch"
  "https://github.com/spring-projects/spring-integration.git                      java          spring-integration"

  # ── java ─────────────────────────────────────────────────────────────
  "https://github.com/macrozheng/mall.git                                         java          mall"
  "https://github.com/apolloconfig/apollo.git                                      java          apollo"
  "https://github.com/alibaba/nacos.git                                            java          nacos"
  "https://github.com/alibaba/Sentinel.git                                         java          sentinel"
  "https://github.com/apache/shardingsphere.git                                    java          shardingsphere"
  "https://github.com/dromara/Sa-Token.git                                         java          sa-token"
  "https://github.com/halo-dev/halo.git                                            java          halo"
  "https://github.com/elunez/eladmin.git                                           java          eladmin"
  "https://github.com/jeecgboot/JeecgBoot.git                                      java          jeecgboot"
  "https://github.com/macrozheng/mall-swarm.git                                    java          mall-swarm"
  "https://github.com/YunaiV/ruoyi-vue-pro.git                                     java          ruoyi-vue-pro"
  "https://github.com/dromara/RuoYi-Vue-Plus.git                                   java          ruoyi-vue-plus"
  "https://github.com/xkcoding/spring-boot-demo.git                                java          spring-boot-demo"
  "https://github.com/hs-web/hsweb-framework.git                                   java          hsweb-framework"
  "https://github.com/doocs/advanced-java.git                                       java          advanced-java"
  "https://github.com/guchengwuyue/yshopmall.git                                    java          yshopmall"
  "https://github.com/cloudfavorites/favorites-web.git                              java          favorites-web"
  "https://github.com/lenve/vhr.git                                                 java          vhr"
  "https://github.com/lihengming/spring-boot-api-project-seed.git                  java          api-project-seed"

  # ── java ────────────────────────────────────────────────────────────
  "https://github.com/alibaba/java-alibaba.git                             java         java-alibaba"
  "https://github.com/java/java-gateway.git                        java         java-gateway"
  "https://github.com/java/java-config.git                         java         java-config"
  "https://github.com/java/java-netflix.git                        java         java-netflix"
  "https://github.com/java/java-openfeign.git                      java         java-openfeign"
  "https://github.com/java/java-sleuth.git                         java         java-sleuth"
  "https://github.com/pig-mesh/pig.git                                              java         pig"
  "https://github.com/sqshq/piggymetrics.git                                        java         piggymetrics"
  "https://github.com/zhoutaoo/SpringCloud.git                                      java         springcloud-learning"
  "https://github.com/forezp/SpringCloudLearning.git                               java         springcloudlearning"
  "https://github.com/yinjihuan/java.git                                    java         yinjihuan-cloud"
  "https://github.com/liuweijw/fw-cloud-framework.git                               java         fw-cloud-framework"
  "https://github.com/itmuch/java-docker-microservice-book-code.git         java         cloud-docker-book"

  # ── java ──────────────────────────────────────────────────────────────
  "https://github.com/apache/kafka.git                                              java           kafka"
  "https://github.com/elastic/elasticsearch.git                                     java           elasticsearch"
  "https://github.com/opensearch-project/OpenSearch.git                             java           opensearch"
  "https://github.com/apache/cassandra.git                                          java           cassandra"
  "https://github.com/jenkinsci/jenkins.git                                         java           jenkins"
  "https://github.com/apache/druid.git                                              java           druid"
  "https://github.com/apache/pulsar.git                                             java           pulsar"
  "https://github.com/apache/flink.git                                              java           flink"
  "https://github.com/trinodb/trino.git                                             java           trino"
  "https://github.com/keycloak/keycloak.git                                         java           keycloak"
  "https://github.com/apache/hadoop.git                                             java           hadoop"
  "https://github.com/apache/spark.git                                              java           spark"
  "https://github.com/apache/hbase.git                                              java           hbase"
  "https://github.com/apache/hive.git                                               java           hive"
  "https://github.com/apache/zookeeper.git                                          java           zookeeper"
  "https://github.com/apache/tomcat.git                                             java           tomcat"
  "https://github.com/eclipse-vertx/vert.x.git                                      java           vertx"
  "https://github.com/netty/netty.git                                               java           netty"
  "https://github.com/google/guava.git                                              java           guava"
  "https://github.com/ReactiveX/RxJava.git                                          java           rxjava"
  "https://github.com/apache/dubbo.git                                              java           dubbo"
  "https://github.com/grpc/grpc-java.git                                            java           grpc-java"
  "https://github.com/square/okhttp.git                                             java           okhttp"
  "https://github.com/apache/beam.git                                               java           beam"
  "https://github.com/prestodb/presto.git                                           java           presto"
  "https://github.com/apache/rocketmq.git                                           java           rocketmq"
  "https://github.com/wildfly/wildfly.git                                           java           wildfly"
  "https://github.com/eclipse/jetty.project.git                                     java           jetty"
  "https://github.com/OpenAPITools/openapi-generator.git                            java           openapi-generator"
  "https://github.com/apache/solr.git                                               java           solr"
  "https://github.com/apache/nifi.git                                               java           nifi"
  "https://github.com/apache/camel.git                                              java           camel"
  "https://github.com/hazelcast/hazelcast.git                                       java           hazelcast"
  "https://github.com/ignite-grid/ignite.git                                        java           ignite"
  "https://github.com/apache/ignite.git                                             java           apache-ignite"
  "https://github.com/eclipse/che.git                                               java           che"

  # ── java ──────────────────────────────────────────────────────────────
  "https://github.com/redisson/redisson.git                                         java           redisson"
  "https://github.com/lettuce-io/lettuce-core.git                                   java           lettuce"
  "https://github.com/ben-manes/caffeine.git                                        java           caffeine"
  "https://github.com/resilience4j/resilience4j.git                                 java           resilience4j"
  "https://github.com/Netflix/Hystrix.git                                           java           hystrix"
  "https://github.com/Netflix/eureka.git                                            java           eureka"
  "https://github.com/Netflix/ribbon.git                                            java           ribbon"
  "https://github.com/OpenFeign/feign.git                                           java           feign"
  "https://github.com/eclipse/microprofile.git                                      java           microprofile"
  "https://github.com/quarkusio/quarkus.git                                         java           quarkus"
  "https://github.com/micronaut-projects/micronaut-core.git                         java           micronaut"
  "https://github.com/helidon-io/helidon.git                                        java           helidon"
  "https://github.com/undertow-io/undertow.git                                      java           undertow"
  "https://github.com/asynchttpclient/async-http-client.git                         java           async-http-client"
  "https://github.com/apache/activemq.git                                           java           activemq"
  "https://github.com/apache/activemq-artemis.git                                   java           activemq-artemis"
  "https://github.com/zeromq/jeromq.git                                             java           jeromq"
  "https://github.com/google/tink.git                                               java           tink"
  "https://github.com/conscrypt/conscrypt.git                                       java           conscrypt"
  "https://github.com/Netflix/zuul.git                                              java           zuul"
  "https://github.com/micrometer-metrics/micrometer.git                             java           micrometer"
  "https://github.com/open-telemetry/opentelemetry-java.git                         java           opentelemetry-java"
  "https://github.com/openzipkin/zipkin.git                                         java           zipkin"
  "https://github.com/open-telemetry/opentelemetry-java-instrumentation.git         java           otel-java-instrumentation"
  "https://github.com/apache/skywalking.git                                         java           skywalking"
  "https://github.com/pinpoint-apm/pinpoint.git                                     java           pinpoint"

  # ── java ───────────────────────────────────────────────────────────────
  "https://github.com/mybatis/mybatis-3.git                                         java            mybatis"
  "https://github.com/baomidou/mybatis-plus.git                                     java            mybatis-plus"
  "https://github.com/hibernate/hibernate-orm.git                                   java            hibernate"
  "https://github.com/jOOQ/jOOQ.git                                                 java            jooq"
  "https://github.com/openjpa/openjpa.git                                           java            openjpa"
  "https://github.com/liquibase/liquibase.git                                       java            liquibase"
  "https://github.com/flyway/flyway.git                                             java            flyway"
  "https://github.com/FasterXML/jackson-databind.git                                java            jackson-databind"
  "https://github.com/FasterXML/jackson-core.git                                    java            jackson-core"
  "https://github.com/FasterXML/jackson-modules-java8.git                           java            jackson-modules-java8"
  "https://github.com/google/gson.git                                               java            gson"
  "https://github.com/apache/avro.git                                               java            avro"
  "https://github.com/apache/parquet-mr.git                                         java            parquet"
  "https://github.com/protocolbuffers/protobuf.git                                  java            protobuf"
  "https://github.com/apache/lucene.git                                             java            lucene"
  "https://github.com/h2database/h2database.git                                     java            h2database"
  "https://github.com/pgjdbc/pgjdbc.git                                             java            pgjdbc"
  "https://github.com/mysql/mysql-connector-j.git                                   java            mysql-connector"
  "https://github.com/brettwooldridge/HikariCP.git                                  java            hikaricp"
  "https://github.com/apache/calcite.git                                            java            calcite"
  "https://github.com/questdb/questdb.git                                           java            questdb"
  "https://github.com/eclipse/jnosql.git                                            java            jnosql"
  "https://github.com/orientechnologies/orientdb.git                                java            orientdb"
  "https://github.com/neo4j/neo4j.git                                               java            neo4j"
  "https://github.com/apache/hbase.git                                              java            hbase-data"

  # ── java ──────────────────────────────────────────────────────────────
  "https://github.com/checkstyle/checkstyle.git                                     java           checkstyle"
  "https://github.com/pmd/pmd.git                                                   java           pmd"
  "https://github.com/spotbugs/spotbugs.git                                         java           spotbugs"
  "https://github.com/jacoco/jacoco.git                                             java           jacoco"
  "https://github.com/junit-team/junit5.git                                         java           junit5"
  "https://github.com/mockito/mockito.git                                           java           mockito"
  "https://github.com/assertj/assertj-core.git                                      java           assertj"
  "https://github.com/testcontainers/testcontainers-java.git                        java           testcontainers"
  "https://github.com/google/error-prone.git                                        java           error-prone"
  "https://github.com/typetools/checker-framework.git                               java           checker-framework"
  "https://github.com/javaparser/javaparser.git                                     java           javaparser"
  "https://github.com/jboss-javassist/javassist.git                                 java           javassist"
  "https://github.com/cglib/cglib.git                                               java           cglib"
  "https://github.com/raphw/byte-buddy.git                                          java           byte-buddy"
  "https://github.com/robolectric/robolectric.git                                   java           robolectric"
  "https://github.com/apache/maven.git                                              java           maven"
  "https://github.com/gradle/gradle.git                                             java           gradle"
  "https://github.com/google/auto.git                                               java           google-auto"
  "https://github.com/square/javapoet.git                                           java           javapoet"
  "https://github.com/rzwitserloot/lombok.git                                       java           lombok"
  "https://github.com/mapstruct/mapstruct.git                                       java           mapstruct"
  "https://github.com/immutables/immutables.git                                     java           immutables"
  "https://github.com/pitest/pitest.git                                             java           pitest"
  "https://github.com/archunit/archunit.git                                         java           archunit"
  "https://github.com/diffplug/spotless.git                                         java           spotless"
  "https://github.com/google/google-java-format.git                                 java           google-java-format"
  "https://github.com/spring-projects/sts4.git                                      java           sts4"
  "https://github.com/eclipse/eclipse.jdt.ls.git                                    java           jdt-ls"

  # ── java ────────────────────────────────────────────────────────────
  "https://github.com/square/retrofit.git                                           java         retrofit"
  "https://github.com/bumptech/glide.git                                            java         glide"
  "https://github.com/square/picasso.git                                            java         picasso"
  "https://github.com/greenrobot/EventBus.git                                       java         eventbus"
  "https://github.com/greenrobot/greenDAO.git                                       java         greendao"
  "https://github.com/JakeWharton/butterknife.git                                   java         butterknife"
  "https://github.com/ReactiveX/RxAndroid.git                                       java         rxandroid"
  "https://github.com/facebook/fresco.git                                           java         fresco"
  "https://github.com/airbnb/lottie-android.git                                     java         lottie"
  "https://github.com/dagger/dagger.git                                             java         dagger"
  "https://github.com/Tencent/tinker.git                                            java         tinker"
  "https://github.com/alibaba/ARouter.git                                           java         arouter"
  "https://github.com/nostra13/Android-Universal-Image-Loader.git                   java         uil"
  "https://github.com/CymChad/BaseRecyclerViewAdapterHelper.git                     java         brvah"
  "https://github.com/zhihu/Matisse.git                                             java         matisse"
  "https://github.com/square/leakcanary.git                                         java         leakcanary"
  "https://github.com/JakeWharton/timber.git                                        java         timber"
  "https://github.com/permissions-dispatcher/PermissionsDispatcher.git              java         permissions-dispatcher"

  # ── java ───────────────────────────────────────────────────────────
  "https://github.com/auth0/java-jwt.git                                            java        java-jwt"
  "https://github.com/jwtk/jjwt.git                                                java        jjwt"
  "https://github.com/pac4j/pac4j.git                                               java        pac4j"
  "https://github.com/bouncycastle/bc-java.git                                      java        bc-java"
  "https://github.com/nimbusds/nimbus-jose-jwt.git                                  java        nimbus-jose-jwt"
  "https://github.com/google/tink.git                                               java        tink-security"
  "https://github.com/shiroproject/shiro.git                                        java        shiro"
  "https://github.com/apereo/cas.git                                                java        cas"
  "https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server.git         java        openid-connect"
  "https://github.com/spring-attic/spring-security-oauth.git                        java        spring-security-oauth"
  "https://github.com/zalando/problem.git                                           java        zalando-problem"
  "https://github.com/OWASP/java-html-sanitizer.git                                java        java-html-sanitizer"
  "https://github.com/spotbugs/spotbugs.git                                         java        spotbugs-security"

  # ── java ─────────────────────────────────────────────────────────────
  "https://github.com/zaproxy/zaproxy.git                                           java          zaproxy"
  "https://github.com/google/guice.git                                              java          guice"
  "https://github.com/dropwizard/dropwizard.git                                     java          dropwizard"
  "https://github.com/graphql-java/graphql-java.git                                 java          graphql-java"
  "https://github.com/apache/commons-lang.git                                       java          commons-lang"
  "https://github.com/apache/commons-collections.git                                java          commons-collections"
  "https://github.com/apache/commons-io.git                                         java          commons-io"
  "https://github.com/apache/commons-codec.git                                      java          commons-codec"
  "https://github.com/apache/commons-compress.git                                   java          commons-compress"
  "https://github.com/apache/poi.git                                                java          poi"
  "https://github.com/apache/pdfbox.git                                             java          pdfbox"
  "https://github.com/apache/tika.git                                               java          tika"
  "https://github.com/jhy/jsoup.git                                                 java          jsoup"
  "https://github.com/skylot/jadx.git                                               java          jadx"
  "https://github.com/google/jimfs.git                                              java          jimfs"
  "https://github.com/openstreetmap/osmosis.git                                     java          osmosis"
  "https://github.com/burningwave/core.git                                          java          burningwave"
  "https://github.com/lionsoul2014/ip2region.git                                    java          ip2region"
  "https://github.com/apache/commons-math.git                                       java          commons-math"
  "https://github.com/apache/commons-text.git                                       java          commons-text"
  "https://github.com/apache/commons-csv.git                                        java          commons-csv"
  "https://github.com/apache/commons-net.git                                        java          commons-net"
  "https://github.com/eclipse/eclipse-collections.git                               java          eclipse-collections"
  "https://github.com/vavr-io/vavr.git                                              java          vavr"
  "https://github.com/amaembo/streamex.git                                          java          streamex"

  # ── java (deliberately vulnerable / benchmark apps) ─────────────────────
  "https://github.com/WebGoat/WebGoat.git                                           java            webgoat"
  "https://github.com/OWASP-Benchmark/BenchmarkJava.git                             java            owasp-benchmark"
  "https://github.com/edu-secmachine/javulna.git                                    java            javulna"
  "https://github.com/JoyChou93/java-sec-code.git                                   java            java-sec-code"
  "https://github.com/appsecco/dvja.git                                             java            dvja"
  "https://github.com/CSPF-Founder/JavaVulnerableLab.git                            java            javavulnerablelab"
  "https://github.com/DataDog/vulnerable-java-application.git                       java            vulnado"
  "https://github.com/Checkmarx/Goatlin.git                                         java            goatlin"
  "https://github.com/OWASP/SecurityShepherd.git                                    java            security-shepherd"
  "https://github.com/righettod/poc-xxe.git                                         java            poc-xxe"
  "https://github.com/righettod/poc-graphql.git                                     java            poc-graphql"
  "https://github.com/snoopysecurity/Vulnerable-Code-Snippets.git                   java            vuln-snippets"
  "https://github.com/frohoff/ysoserial.git                                         java            ysoserial"
  "https://github.com/GrrrDog/Java-Deserialization-Cheat-Sheet.git                  java            java-deser-cheatsheet"
  "https://github.com/jaiswalakshansh/Damn-Vulnerable-GraphQL-Application.git       java            dvga-java"
)
