#!/usr/bin/env bash
# node.sh — Node.js / TypeScript / npm OSS repo catalog
#
# Provides: NODE_REPOS array  (sourced by master.sh)
# Format per entry: "<clone-url>  <category>  <dir-name>"
#
# Categories:
#   node    node   node
#   node node
# ─────────────────────────────────────────────────────────────────────────────
[[ -n "${_NODE_SH_LOADED:-}" ]] && return 0
_NODE_SH_LOADED=1

NODE_REPOS=(

  # ── node ──────────────────────────────────────────────────────────────
  "https://github.com/nodejs/node.git                                               node        node"
  "https://github.com/expressjs/express.git                                         node        express"
  "https://github.com/nestjs/nest.git                                               node        nest"
  "https://github.com/facebook/react.git                                            node        react"
  "https://github.com/vuejs/vue.git                                                 node        vue"
  "https://github.com/vuejs/core.git                                                node        vue-core"
  "https://github.com/angular/angular.git                                           node        angular"
  "https://github.com/webpack/webpack.git                                           node        webpack"
  "https://github.com/vitejs/vite.git                                               node        vite"
  "https://github.com/eslint/eslint.git                                             node        eslint"
  "https://github.com/prettier/prettier.git                                         node        prettier"
  "https://github.com/lodash/lodash.git                                             node        lodash"
  "https://github.com/axios/axios.git                                               node        axios"
  "https://github.com/socketio/socket.io.git                                        node        socketio"
  "https://github.com/typescript-eslint/typescript-eslint.git                       node        typescript-eslint"
  "https://github.com/mochajs/mocha.git                                             node        mocha"
  "https://github.com/jestjs/jest.git                                               node        jest"
  "https://github.com/vercel/next.js.git                                            node        nextjs"
  "https://github.com/nuxt/nuxt.git                                                 node        nuxt"
  "https://github.com/microsoft/TypeScript.git                                      node        typescript"
  "https://github.com/denoland/deno.git                                             node        deno"
  "https://github.com/evanw/esbuild.git                                             node        esbuild"
  "https://github.com/rollup/rollup.git                                             node        rollup"
  "https://github.com/parcel-bundler/parcel.git                                     node        parcel"
  "https://github.com/babel/babel.git                                               node        babel"
  "https://github.com/graphql/graphql-js.git                                        node        graphql-js"
  "https://github.com/apollographql/apollo-server.git                               node        apollo-server"
  "https://github.com/trpc/trpc.git                                                 node        trpc"
  "https://github.com/colinhacks/zod.git                                            node        zod"

  # ── node ─────────────────────────────────────────────────────────────
  "https://github.com/fastify/fastify.git                                           node       fastify"
  "https://github.com/koajs/koa.git                                                 node       koa"
  "https://github.com/hapijs/hapi.git                                               node       hapi"
  "https://github.com/remix-run/remix.git                                           node       remix"
  "https://github.com/gatsbyjs/gatsby.git                                           node       gatsby"
  "https://github.com/sveltejs/svelte.git                                           node       svelte"
  "https://github.com/reduxjs/redux.git                                             node       redux"
  "https://github.com/date-fns/date-fns.git                                         node       date-fns"
  "https://github.com/TypeStrong/ts-node.git                                        node       ts-node"
  "https://github.com/pmndrs/zustand.git                                            node       zustand"
  "https://github.com/TanStack/query.git                                            node       tanstack-query"
  "https://github.com/payloadcms/payload.git                                        node       payload"
  "https://github.com/strapi/strapi.git                                             node       strapi"
  "https://github.com/sequelize/sequelize.git                                       node       sequelize"
  "https://github.com/prisma/prisma.git                                             node       prisma"
  "https://github.com/typeorm/typeorm.git                                           node       typeorm"
  "https://github.com/mikro-orm/mikro-orm.git                                       node       mikro-orm"
  "https://github.com/keystonejs/keystone.git                                       node       keystone"
  "https://github.com/directus/directus.git                                         node       directus"
  "https://github.com/hasura/graphql-engine.git                                     node       hasura"
  "https://github.com/withastro/astro.git                                           node       astro"
  "https://github.com/solidjs/solid.git                                             node       solid"
  "https://github.com/preactjs/preact.git                                           node       preact"
  "https://github.com/alpinejs/alpine.git                                           node       alpine"
  "https://github.com/pmndrs/jotai.git                                              node       jotai"
  "https://github.com/mobxjs/mobx.git                                               node       mobx"
  "https://github.com/immerjs/immer.git                                             node       immer"
  "https://github.com/ava-labs/avalanchejs.git                                      node       avalanchejs"
  "https://github.com/vercel/turbo.git                                              node       turbo"
  "https://github.com/pnpm/pnpm.git                                                 node       pnpm"

  # ── node ──────────────────────────────────────────────────────────────
  "https://github.com/tj/commander.js.git                                           node        commander"
  "https://github.com/yargs/yargs.git                                               node        yargs"
  "https://github.com/chalk/chalk.git                                               node        chalk"
  "https://github.com/sindresorhus/execa.git                                        node        execa"
  "https://github.com/sindresorhus/got.git                                          node        got"
  "https://github.com/node-fetch/node-fetch.git                                     node        node-fetch"
  "https://github.com/dotenv-org/dotenv.git                                         node        dotenv"
  "https://github.com/isaacs/node-glob.git                                          node        glob"
  "https://github.com/micromatch/micromatch.git                                     node        micromatch"
  "https://github.com/jprichardson/node-fs-extra.git                                node        fs-extra"
  "https://github.com/isaacs/rimraf.git                                             node        rimraf"
  "https://github.com/caolan/async.git                                              node        async"
  "https://github.com/debug-js/debug.git                                            node        debug"
  "https://github.com/winstonjs/winston.git                                         node        winston"
  "https://github.com/pinojs/pino.git                                               node        pino"
  "https://github.com/node-serialport/node-serialport.git                           node        serialport"
  "https://github.com/websockets/ws.git                                             node        ws"
  "https://github.com/uuidjs/uuid.git                                               node        uuid"
  "https://github.com/knex/knex.git                                                 node        knex"
  "https://github.com/brianc/node-postgres.git                                      node        node-postgres"

  # ── node ───────────────────────────────────────────────────────────
  "https://github.com/auth0/node-jsonwebtoken.git                                   node     jsonwebtoken"
  "https://github.com/panva/jose.git                                                node     jose"
  "https://github.com/jaredhanson/passport.git                                      node     passport"
  "https://github.com/jaredhanson/passport-jwt.git                                  node     passport-jwt"
  "https://github.com/kelektiv/node.bcrypt.js.git                                   node     bcryptjs"
  "https://github.com/dcodeIO/bcrypt.js.git                                         node     bcrypt-js"
  "https://github.com/crypto-browserify/browserify-sign.git                         node     browserify-sign"
  "https://github.com/auth0/node-oauth2-jwt-bearer.git                              node     oauth2-jwt-bearer"
  "https://github.com/simov/grant.git                                               node     grant"
  "https://github.com/mozilla/node-convict.git                                      node     node-convict"
  "https://github.com/helmetjs/helmet.git                                           node     helmet"
  "https://github.com/expressjs/cors.git                                            node     cors"
  "https://github.com/expressjs/session.git                                         node     express-session"
  "https://github.com/visionmedia/node-querystring.git                              node     node-querystring"
  "https://github.com/mysticatea/eslint-plugin-security.git                         node     eslint-plugin-security"

  # ── node ───────────────────────────────────────────────────────────────
  "https://github.com/OWASP/NodeGoat.git                                            node         nodegoat"
  "https://github.com/juice-shop/juice-shop.git                                     node         juice-shop"
  "https://github.com/Contrast-Security-OSS/NodeGoat.git                            node         contrast-nodegoat"
  "https://github.com/OWASP/DVNA.git                                                node         dvna"
  "https://github.com/OWASP/secureflag-os.git                                       node         secureflag-os"
  "https://github.com/snyk-labs/nodejs-goof.git                                     node         nodejs-goof"
  "https://github.com/rapid7/NodeGoatPro.git                                        node         nodegoat-pro"
  "https://github.com/cr0hn/vulnerable-node.git                                     node         vulnerable-node"
  "https://github.com/appsecco/dvna.git                                             node         dvna-appsecco"
  "https://github.com/webpwnized/mutillidae.git                                     node         mutillidae"
)
