#!/usr/bin/env bash
# node.sh — Node.js / TypeScript / npm OSS repo catalog
#
# Provides: NODE_REPOS array  (sourced by master.sh)
# Format per entry: "<clone-url>  <category>  <dir-name>"
#
# Categories:
#   node-large    node-medium   node-tools
#   node-security node-sast
# ─────────────────────────────────────────────────────────────────────────────
[[ -n "${_NODE_SH_LOADED:-}" ]] && return 0
_NODE_SH_LOADED=1

NODE_REPOS=(

  # ── node-large ──────────────────────────────────────────────────────────────
  "https://github.com/nodejs/node.git                                               node-large        node"
  "https://github.com/expressjs/express.git                                         node-large        express"
  "https://github.com/nestjs/nest.git                                               node-large        nest"
  "https://github.com/facebook/react.git                                            node-large        react"
  "https://github.com/vuejs/vue.git                                                 node-large        vue"
  "https://github.com/vuejs/core.git                                                node-large        vue-core"
  "https://github.com/angular/angular.git                                           node-large        angular"
  "https://github.com/webpack/webpack.git                                           node-large        webpack"
  "https://github.com/vitejs/vite.git                                               node-large        vite"
  "https://github.com/eslint/eslint.git                                             node-large        eslint"
  "https://github.com/prettier/prettier.git                                         node-large        prettier"
  "https://github.com/lodash/lodash.git                                             node-large        lodash"
  "https://github.com/axios/axios.git                                               node-large        axios"
  "https://github.com/socketio/socket.io.git                                        node-large        socketio"
  "https://github.com/typescript-eslint/typescript-eslint.git                       node-large        typescript-eslint"
  "https://github.com/mochajs/mocha.git                                             node-large        mocha"
  "https://github.com/jestjs/jest.git                                               node-large        jest"
  "https://github.com/vercel/next.js.git                                            node-large        nextjs"
  "https://github.com/nuxt/nuxt.git                                                 node-large        nuxt"
  "https://github.com/microsoft/TypeScript.git                                      node-large        typescript"
  "https://github.com/denoland/deno.git                                             node-large        deno"
  "https://github.com/evanw/esbuild.git                                             node-large        esbuild"
  "https://github.com/rollup/rollup.git                                             node-large        rollup"
  "https://github.com/parcel-bundler/parcel.git                                     node-large        parcel"
  "https://github.com/babel/babel.git                                               node-large        babel"
  "https://github.com/graphql/graphql-js.git                                        node-large        graphql-js"
  "https://github.com/apollographql/apollo-server.git                               node-large        apollo-server"
  "https://github.com/trpc/trpc.git                                                 node-large        trpc"
  "https://github.com/colinhacks/zod.git                                            node-large        zod"

  # ── node-medium ─────────────────────────────────────────────────────────────
  "https://github.com/fastify/fastify.git                                           node-medium       fastify"
  "https://github.com/koajs/koa.git                                                 node-medium       koa"
  "https://github.com/hapijs/hapi.git                                               node-medium       hapi"
  "https://github.com/remix-run/remix.git                                           node-medium       remix"
  "https://github.com/gatsbyjs/gatsby.git                                           node-medium       gatsby"
  "https://github.com/sveltejs/svelte.git                                           node-medium       svelte"
  "https://github.com/reduxjs/redux.git                                             node-medium       redux"
  "https://github.com/date-fns/date-fns.git                                         node-medium       date-fns"
  "https://github.com/TypeStrong/ts-node.git                                        node-medium       ts-node"
  "https://github.com/pmndrs/zustand.git                                            node-medium       zustand"
  "https://github.com/TanStack/query.git                                            node-medium       tanstack-query"
  "https://github.com/payloadcms/payload.git                                        node-medium       payload"
  "https://github.com/strapi/strapi.git                                             node-medium       strapi"
  "https://github.com/sequelize/sequelize.git                                       node-medium       sequelize"
  "https://github.com/prisma/prisma.git                                             node-medium       prisma"
  "https://github.com/typeorm/typeorm.git                                           node-medium       typeorm"
  "https://github.com/mikro-orm/mikro-orm.git                                       node-medium       mikro-orm"
  "https://github.com/keystonejs/keystone.git                                       node-medium       keystone"
  "https://github.com/directus/directus.git                                         node-medium       directus"
  "https://github.com/hasura/graphql-engine.git                                     node-medium       hasura"
  "https://github.com/withastro/astro.git                                           node-medium       astro"
  "https://github.com/solidjs/solid.git                                             node-medium       solid"
  "https://github.com/preactjs/preact.git                                           node-medium       preact"
  "https://github.com/alpinejs/alpine.git                                           node-medium       alpine"
  "https://github.com/pmndrs/jotai.git                                              node-medium       jotai"
  "https://github.com/mobxjs/mobx.git                                               node-medium       mobx"
  "https://github.com/immerjs/immer.git                                             node-medium       immer"
  "https://github.com/ava-labs/avalanchejs.git                                      node-medium       avalanchejs"
  "https://github.com/vercel/turbo.git                                              node-medium       turbo"
  "https://github.com/pnpm/pnpm.git                                                 node-medium       pnpm"

  # ── node-tools ──────────────────────────────────────────────────────────────
  "https://github.com/tj/commander.js.git                                           node-tools        commander"
  "https://github.com/yargs/yargs.git                                               node-tools        yargs"
  "https://github.com/chalk/chalk.git                                               node-tools        chalk"
  "https://github.com/sindresorhus/execa.git                                        node-tools        execa"
  "https://github.com/sindresorhus/got.git                                          node-tools        got"
  "https://github.com/node-fetch/node-fetch.git                                     node-tools        node-fetch"
  "https://github.com/dotenv-org/dotenv.git                                         node-tools        dotenv"
  "https://github.com/isaacs/node-glob.git                                          node-tools        glob"
  "https://github.com/micromatch/micromatch.git                                     node-tools        micromatch"
  "https://github.com/jprichardson/node-fs-extra.git                                node-tools        fs-extra"
  "https://github.com/isaacs/rimraf.git                                             node-tools        rimraf"
  "https://github.com/caolan/async.git                                              node-tools        async"
  "https://github.com/debug-js/debug.git                                            node-tools        debug"
  "https://github.com/winstonjs/winston.git                                         node-tools        winston"
  "https://github.com/pinojs/pino.git                                               node-tools        pino"
  "https://github.com/node-serialport/node-serialport.git                           node-tools        serialport"
  "https://github.com/websockets/ws.git                                             node-tools        ws"
  "https://github.com/uuidjs/uuid.git                                               node-tools        uuid"
  "https://github.com/knex/knex.git                                                 node-tools        knex"
  "https://github.com/brianc/node-postgres.git                                      node-tools        node-postgres"

  # ── node-security ───────────────────────────────────────────────────────────
  "https://github.com/auth0/node-jsonwebtoken.git                                   node-security     jsonwebtoken"
  "https://github.com/panva/jose.git                                                node-security     jose"
  "https://github.com/jaredhanson/passport.git                                      node-security     passport"
  "https://github.com/jaredhanson/passport-jwt.git                                  node-security     passport-jwt"
  "https://github.com/kelektiv/node.bcrypt.js.git                                   node-security     bcryptjs"
  "https://github.com/dcodeIO/bcrypt.js.git                                         node-security     bcrypt-js"
  "https://github.com/crypto-browserify/browserify-sign.git                         node-security     browserify-sign"
  "https://github.com/auth0/node-oauth2-jwt-bearer.git                              node-security     oauth2-jwt-bearer"
  "https://github.com/simov/grant.git                                               node-security     grant"
  "https://github.com/mozilla/node-convict.git                                      node-security     node-convict"
  "https://github.com/helmetjs/helmet.git                                           node-security     helmet"
  "https://github.com/expressjs/cors.git                                            node-security     cors"
  "https://github.com/expressjs/session.git                                         node-security     express-session"
  "https://github.com/visionmedia/node-querystring.git                              node-security     node-querystring"
  "https://github.com/mysticatea/eslint-plugin-security.git                         node-security     eslint-plugin-security"

  # ── node-sast ───────────────────────────────────────────────────────────────
  "https://github.com/OWASP/NodeGoat.git                                            node-sast         nodegoat"
  "https://github.com/juice-shop/juice-shop.git                                     node-sast         juice-shop"
  "https://github.com/Contrast-Security-OSS/NodeGoat.git                            node-sast         contrast-nodegoat"
  "https://github.com/OWASP/DVNA.git                                                node-sast         dvna"
  "https://github.com/OWASP/secureflag-os.git                                       node-sast         secureflag-os"
  "https://github.com/snyk-labs/nodejs-goof.git                                     node-sast         nodejs-goof"
  "https://github.com/rapid7/NodeGoatPro.git                                        node-sast         nodegoat-pro"
  "https://github.com/cr0hn/vulnerable-node.git                                     node-sast         vulnerable-node"
  "https://github.com/appsecco/dvna.git                                             node-sast         dvna-appsecco"
  "https://github.com/webpwnized/mutillidae.git                                     node-sast         mutillidae"
)
