#!/usr/bin/env bash
# python.sh — Python OSS repo catalog
#
# Provides: PYTHON_REPOS array  (sourced by master.sh)
# Format per entry: "<clone-url>  <category>  <dir-name>"
#
# Categories:
#   python   python  python
#   python    python   python  python
# ─────────────────────────────────────────────────────────────────────────────
[[ -n "${_PYTHON_SH_LOADED:-}" ]] && return 0
_PYTHON_SH_LOADED=1

PYTHON_REPOS=(

  # ── python ────────────────────────────────────────────────────────────
  "https://github.com/django/django.git                                             python      django"
  "https://github.com/pallets/flask.git                                             python      flask"
  "https://github.com/fastapi/fastapi.git                                           python      fastapi"
  "https://github.com/numpy/numpy.git                                               python      numpy"
  "https://github.com/pandas-dev/pandas.git                                         python      pandas"
  "https://github.com/psf/requests.git                                              python      requests"
  "https://github.com/ansible/ansible.git                                           python      ansible"
  "https://github.com/apache/airflow.git                                            python      airflow"
  "https://github.com/celery/celery.git                                             python      celery"
  "https://github.com/redis/redis-py.git                                            python      redis-py"
  "https://github.com/pytest-dev/pytest.git                                         python      pytest"
  "https://github.com/sqlalchemy/sqlalchemy.git                                     python      sqlalchemy"
  "https://github.com/aio-libs/aiohttp.git                                          python      aiohttp"
  "https://github.com/huggingface/transformers.git                                  python      transformers"
  "https://github.com/scikit-learn/scikit-learn.git                                 python      scikit-learn"
  "https://github.com/scipy/scipy.git                                               python      scipy"
  "https://github.com/matplotlib/matplotlib.git                                     python      matplotlib"
  "https://github.com/encode/uvicorn.git                                            python      uvicorn"
  "https://github.com/python-poetry/poetry.git                                      python      poetry"
  "https://github.com/pypa/pip.git                                                  python      pip"
  "https://github.com/astral-sh/ruff.git                                            python      ruff"
  "https://github.com/python/cpython.git                                            python      cpython"
  "https://github.com/tornadoweb/tornado.git                                        python      tornado"
  "https://github.com/encode/starlette.git                                          python      starlette"
  "https://github.com/pydantic/pydantic.git                                         python      pydantic"
  "https://github.com/boto/boto3.git                                                python      boto3"
  "https://github.com/google/grpc.git                                               python      grpc"
  "https://github.com/paramiko/paramiko.git                                         python      paramiko"
  "https://github.com/pyca/cryptography.git                                         python      cryptography"

  # ── python ───────────────────────────────────────────────────────────
  "https://github.com/streamlit/streamlit.git                                       python     streamlit"
  "https://github.com/scrapy/scrapy.git                                             python     scrapy"
  "https://github.com/Textualize/rich.git                                           python     rich"
  "https://github.com/getsentry/sentry.git                                          python     sentry"
  "https://github.com/apache/superset.git                                           python     superset"
  "https://github.com/frappe/frappe.git                                             python     frappe"
  "https://github.com/falconry/falcon.git                                           python     falcon"
  "https://github.com/Pylons/pyramid.git                                            python     pyramid"
  "https://github.com/bottlepy/bottle.git                                           python     bottle"
  "https://github.com/yaml/pyyaml.git                                               python     pyyaml"
  "https://github.com/python-pillow/Pillow.git                                      python     pillow"
  "https://github.com/pallets/click.git                                             python     click"
  "https://github.com/python/mypy.git                                               python     mypy"
  "https://github.com/pylint-dev/pylint.git                                         python     pylint"
  "https://github.com/python-lsp/python-lsp-server.git                              python     python-lsp-server"
  "https://github.com/encode/httpx.git                                              python     httpx"
  "https://github.com/tiangolo/sqlmodel.git                                         python     sqlmodel"
  "https://github.com/benoitc/gunicorn.git                                          python     gunicorn"
  "https://github.com/joke2k/faker.git                                              python     faker"
  "https://github.com/dateutil/dateutil.git                                         python     dateutil"
  "https://github.com/arrow-py/arrow.git                                            python     arrow"
  "https://github.com/tartley/colorama.git                                          python     colorama"
  "https://github.com/Textualize/textual.git                                        python     textual"
  "https://github.com/tqdm/tqdm.git                                                 python     tqdm"

  # ── python ──────────────────────────────────────────────────────────────
  "https://github.com/cookiecutter/cookiecutter-django.git                          python        cookiecutter-django"
  "https://github.com/saleor/saleor.git                                             python        saleor"
  "https://github.com/zulip/zulip.git                                               python        zulip"
  "https://github.com/readthedocs/readthedocs.org.git                               python        readthedocs"
  "https://github.com/django-cms/django-cms.git                                     python        django-cms"
  "https://github.com/mage-ai/mage-ai.git                                           python        mage-ai"
  "https://github.com/posthog/posthog.git                                           python        posthog"
  "https://github.com/netbox-community/netbox.git                                   python        netbox"
  "https://github.com/healthchecks/healthchecks.git                                 python        healthchecks"
  "https://github.com/mayan-edms/Mayan-EDMS.git                                     python        mayan-edms"
  "https://github.com/wagtail/wagtail.git                                           python        wagtail"
  "https://github.com/encode/django-rest-framework.git                              python        django-rest-framework"
  "https://github.com/jazzband/django-oauth-toolkit.git                             python        django-oauth-toolkit"
  "https://github.com/jazzband/django-rest-knox.git                                 python        django-rest-knox"
  "https://github.com/pennersr/django-allauth.git                                   python        django-allauth"
  "https://github.com/django-guardian/django-guardian.git                           python        django-guardian"
  "https://github.com/joke2k/django-environ.git                                     python        django-environ"
  "https://github.com/un33k/python-slugify.git                                      python        python-slugify"
  "https://github.com/jazzband/django-debug-toolbar.git                             python        django-debug-toolbar"
  "https://github.com/jazzband/django-silk.git                                      python        django-silk"

  # ── python ─────────────────────────────────────────────────────────────
  "https://github.com/pytorch/pytorch.git                                           python       pytorch"
  "https://github.com/tensorflow/tensorflow.git                                     python       tensorflow"
  "https://github.com/dmlc/xgboost.git                                              python       xgboost"
  "https://github.com/microsoft/LightGBM.git                                        python       lightgbm"
  "https://github.com/mlflow/mlflow.git                                             python       mlflow"
  "https://github.com/ray-project/ray.git                                           python       ray"
  "https://github.com/dask/dask.git                                                 python       dask"
  "https://github.com/jupyter/notebook.git                                          python       jupyter-notebook"
  "https://github.com/pola-rs/polars.git                                            python       polars"
  "https://github.com/duckdb/duckdb.git                                             python       duckdb"
  "https://github.com/sympy/sympy.git                                               python       sympy"
  "https://github.com/networkx/networkx.git                                         python       networkx"
  "https://github.com/plotly/plotly.py.git                                          python       plotly"
  "https://github.com/altair-viz/altair.git                                         python       altair"
  "https://github.com/bokeh/bokeh.git                                               python       bokeh"
  "https://github.com/apache/arrow.git                                              python       arrow-python"
  "https://github.com/ibis-project/ibis.git                                         python       ibis"

  # ── python ────────────────────────────────────────────────────────────
  "https://github.com/psf/black.git                                                 python      black"
  "https://github.com/PyCQA/bandit.git                                              python      bandit"
  "https://github.com/PyCQA/flake8.git                                              python      flake8"
  "https://github.com/python/typeshed.git                                           python      typeshed"
  "https://github.com/davidhalter/jedi.git                                          python      jedi"
  "https://github.com/pyupio/safety.git                                             python      safety"
  "https://github.com/trailofbits/pip-audit.git                                     python      pip-audit"
  "https://github.com/semgrep/semgrep.git                                           python      semgrep"
  "https://github.com/pypa/setuptools.git                                           python      setuptools"
  "https://github.com/pypa/hatch.git                                                python      hatch"
  "https://github.com/pre-commit/pre-commit.git                                     python      pre-commit"
  "https://github.com/PyCQA/isort.git                                               python      isort"
  "https://github.com/asottile/pyupgrade.git                                        python      pyupgrade"
  "https://github.com/PyCQA/autoflake.git                                           python      autoflake"
  "https://github.com/psutil/psutil.git                                             python      psutil"
  "https://github.com/giampaolo/pyftpdlib.git                                       python      pyftpdlib"
  "https://github.com/Delgan/loguru.git                                             python      loguru"
  "https://github.com/willmcgugan/rich.git                                          python      rich-tools"

  # ── python ─────────────────────────────────────────────────────────
  "https://github.com/pyca/cryptography.git                                         python   cryptography-sec"
  "https://github.com/pyca/pyopenssl.git                                            python   pyopenssl"
  "https://github.com/pyca/bcrypt.git                                               python   bcrypt"
  "https://github.com/pyca/pynacl.git                                               python   pynacl"
  "https://github.com/jpadilla/pyjwt.git                                            python   pyjwt"
  "https://github.com/oauthlib/oauthlib.git                                         python   oauthlib"
  "https://github.com/requests/requests-oauthlib.git                                python   requests-oauthlib"
  "https://github.com/mpdavis/python-jose.git                                       python   python-jose"
  "https://github.com/mozilla/bleach.git                                             python   bleach"
  "https://github.com/scrapy/scrapy.git                                             python   scrapy-sec"

  # ── python ─────────────────────────────────────────────────────────────
  "https://github.com/fportantier/vulpy.git                                         python       vulpy"
  "https://github.com/adeyosemanputera/pygoat.git                                   python       pygoat"
  "https://github.com/Contrast-Security-OSS/vulnpy.git                              python       vulnpy"
  "https://github.com/erev0s/VAmPI.git                                              python       vampi"
  "https://github.com/Checkmarx/Vulnerable-Web-Application.git                      python       checkmarx-vuln-web"
  "https://github.com/stamparm/DVWA-Python.git                                      python       dvwa-python"
  "https://github.com/righettod/poc-zip-slip.git                                    python       poc-zip-slip"
  "https://github.com/we45/Vulnerable-Flask-App.git                                 python       vulnerable-flask"
  "https://github.com/Securecodebox/django-DefectDojo.git                           python       defectdojo"
  "https://github.com/DefectDojo/django-DefectDojo.git                              python       defectdojo-main"
)
