#!/usr/bin/env bash
# python.sh — Python OSS repo catalog
#
# Provides: PYTHON_REPOS array  (sourced by master.sh)
# Format per entry: "<clone-url>  <category>  <dir-name>"
#
# Categories:
#   python-large   python-medium  python-web
#   python-data    python-tools   python-security  python-sast
# ─────────────────────────────────────────────────────────────────────────────
[[ -n "${_PYTHON_SH_LOADED:-}" ]] && return 0
_PYTHON_SH_LOADED=1

PYTHON_REPOS=(

  # ── python-large ────────────────────────────────────────────────────────────
  "https://github.com/django/django.git                                             python-large      django"
  "https://github.com/pallets/flask.git                                             python-large      flask"
  "https://github.com/fastapi/fastapi.git                                           python-large      fastapi"
  "https://github.com/numpy/numpy.git                                               python-large      numpy"
  "https://github.com/pandas-dev/pandas.git                                         python-large      pandas"
  "https://github.com/psf/requests.git                                              python-large      requests"
  "https://github.com/ansible/ansible.git                                           python-large      ansible"
  "https://github.com/apache/airflow.git                                            python-large      airflow"
  "https://github.com/celery/celery.git                                             python-large      celery"
  "https://github.com/redis/redis-py.git                                            python-large      redis-py"
  "https://github.com/pytest-dev/pytest.git                                         python-large      pytest"
  "https://github.com/sqlalchemy/sqlalchemy.git                                     python-large      sqlalchemy"
  "https://github.com/aio-libs/aiohttp.git                                          python-large      aiohttp"
  "https://github.com/huggingface/transformers.git                                  python-large      transformers"
  "https://github.com/scikit-learn/scikit-learn.git                                 python-large      scikit-learn"
  "https://github.com/scipy/scipy.git                                               python-large      scipy"
  "https://github.com/matplotlib/matplotlib.git                                     python-large      matplotlib"
  "https://github.com/encode/uvicorn.git                                            python-large      uvicorn"
  "https://github.com/python-poetry/poetry.git                                      python-large      poetry"
  "https://github.com/pypa/pip.git                                                  python-large      pip"
  "https://github.com/astral-sh/ruff.git                                            python-large      ruff"
  "https://github.com/python/cpython.git                                            python-large      cpython"
  "https://github.com/tornadoweb/tornado.git                                        python-large      tornado"
  "https://github.com/encode/starlette.git                                          python-large      starlette"
  "https://github.com/pydantic/pydantic.git                                         python-large      pydantic"
  "https://github.com/boto/boto3.git                                                python-large      boto3"
  "https://github.com/google/grpc.git                                               python-large      grpc"
  "https://github.com/paramiko/paramiko.git                                         python-large      paramiko"
  "https://github.com/pyca/cryptography.git                                         python-large      cryptography"

  # ── python-medium ───────────────────────────────────────────────────────────
  "https://github.com/streamlit/streamlit.git                                       python-medium     streamlit"
  "https://github.com/scrapy/scrapy.git                                             python-medium     scrapy"
  "https://github.com/Textualize/rich.git                                           python-medium     rich"
  "https://github.com/getsentry/sentry.git                                          python-medium     sentry"
  "https://github.com/apache/superset.git                                           python-medium     superset"
  "https://github.com/frappe/frappe.git                                             python-medium     frappe"
  "https://github.com/falconry/falcon.git                                           python-medium     falcon"
  "https://github.com/Pylons/pyramid.git                                            python-medium     pyramid"
  "https://github.com/bottlepy/bottle.git                                           python-medium     bottle"
  "https://github.com/yaml/pyyaml.git                                               python-medium     pyyaml"
  "https://github.com/python-pillow/Pillow.git                                      python-medium     pillow"
  "https://github.com/pallets/click.git                                             python-medium     click"
  "https://github.com/python/mypy.git                                               python-medium     mypy"
  "https://github.com/pylint-dev/pylint.git                                         python-medium     pylint"
  "https://github.com/python-lsp/python-lsp-server.git                              python-medium     python-lsp-server"
  "https://github.com/encode/httpx.git                                              python-medium     httpx"
  "https://github.com/tiangolo/sqlmodel.git                                         python-medium     sqlmodel"
  "https://github.com/benoitc/gunicorn.git                                          python-medium     gunicorn"
  "https://github.com/joke2k/faker.git                                              python-medium     faker"
  "https://github.com/dateutil/dateutil.git                                         python-medium     dateutil"
  "https://github.com/arrow-py/arrow.git                                            python-medium     arrow"
  "https://github.com/tartley/colorama.git                                          python-medium     colorama"
  "https://github.com/Textualize/textual.git                                        python-medium     textual"
  "https://github.com/tqdm/tqdm.git                                                 python-medium     tqdm"

  # ── python-web ──────────────────────────────────────────────────────────────
  "https://github.com/cookiecutter/cookiecutter-django.git                          python-web        cookiecutter-django"
  "https://github.com/saleor/saleor.git                                             python-web        saleor"
  "https://github.com/zulip/zulip.git                                               python-web        zulip"
  "https://github.com/readthedocs/readthedocs.org.git                               python-web        readthedocs"
  "https://github.com/django-cms/django-cms.git                                     python-web        django-cms"
  "https://github.com/mage-ai/mage-ai.git                                           python-web        mage-ai"
  "https://github.com/posthog/posthog.git                                           python-web        posthog"
  "https://github.com/netbox-community/netbox.git                                   python-web        netbox"
  "https://github.com/healthchecks/healthchecks.git                                 python-web        healthchecks"
  "https://github.com/mayan-edms/Mayan-EDMS.git                                     python-web        mayan-edms"
  "https://github.com/wagtail/wagtail.git                                           python-web        wagtail"
  "https://github.com/encode/django-rest-framework.git                              python-web        django-rest-framework"
  "https://github.com/jazzband/django-oauth-toolkit.git                             python-web        django-oauth-toolkit"
  "https://github.com/jazzband/django-rest-knox.git                                 python-web        django-rest-knox"
  "https://github.com/pennersr/django-allauth.git                                   python-web        django-allauth"
  "https://github.com/django-guardian/django-guardian.git                           python-web        django-guardian"
  "https://github.com/joke2k/django-environ.git                                     python-web        django-environ"
  "https://github.com/un33k/python-slugify.git                                      python-web        python-slugify"
  "https://github.com/jazzband/django-debug-toolbar.git                             python-web        django-debug-toolbar"
  "https://github.com/jazzband/django-silk.git                                      python-web        django-silk"

  # ── python-data ─────────────────────────────────────────────────────────────
  "https://github.com/pytorch/pytorch.git                                           python-data       pytorch"
  "https://github.com/tensorflow/tensorflow.git                                     python-data       tensorflow"
  "https://github.com/dmlc/xgboost.git                                              python-data       xgboost"
  "https://github.com/microsoft/LightGBM.git                                        python-data       lightgbm"
  "https://github.com/mlflow/mlflow.git                                             python-data       mlflow"
  "https://github.com/ray-project/ray.git                                           python-data       ray"
  "https://github.com/dask/dask.git                                                 python-data       dask"
  "https://github.com/jupyter/notebook.git                                          python-data       jupyter-notebook"
  "https://github.com/pola-rs/polars.git                                            python-data       polars"
  "https://github.com/duckdb/duckdb.git                                             python-data       duckdb"
  "https://github.com/sympy/sympy.git                                               python-data       sympy"
  "https://github.com/networkx/networkx.git                                         python-data       networkx"
  "https://github.com/plotly/plotly.py.git                                          python-data       plotly"
  "https://github.com/altair-viz/altair.git                                         python-data       altair"
  "https://github.com/bokeh/bokeh.git                                               python-data       bokeh"
  "https://github.com/apache/arrow.git                                              python-data       arrow-python"
  "https://github.com/ibis-project/ibis.git                                         python-data       ibis"

  # ── python-tools ────────────────────────────────────────────────────────────
  "https://github.com/psf/black.git                                                 python-tools      black"
  "https://github.com/PyCQA/bandit.git                                              python-tools      bandit"
  "https://github.com/PyCQA/flake8.git                                              python-tools      flake8"
  "https://github.com/python/typeshed.git                                           python-tools      typeshed"
  "https://github.com/davidhalter/jedi.git                                          python-tools      jedi"
  "https://github.com/pyupio/safety.git                                             python-tools      safety"
  "https://github.com/trailofbits/pip-audit.git                                     python-tools      pip-audit"
  "https://github.com/semgrep/semgrep.git                                           python-tools      semgrep"
  "https://github.com/pypa/setuptools.git                                           python-tools      setuptools"
  "https://github.com/pypa/hatch.git                                                python-tools      hatch"
  "https://github.com/pre-commit/pre-commit.git                                     python-tools      pre-commit"
  "https://github.com/PyCQA/isort.git                                               python-tools      isort"
  "https://github.com/asottile/pyupgrade.git                                        python-tools      pyupgrade"
  "https://github.com/PyCQA/autoflake.git                                           python-tools      autoflake"
  "https://github.com/psutil/psutil.git                                             python-tools      psutil"
  "https://github.com/giampaolo/pyftpdlib.git                                       python-tools      pyftpdlib"
  "https://github.com/Delgan/loguru.git                                             python-tools      loguru"
  "https://github.com/willmcgugan/rich.git                                          python-tools      rich-tools"

  # ── python-security ─────────────────────────────────────────────────────────
  "https://github.com/pyca/cryptography.git                                         python-security   cryptography-sec"
  "https://github.com/pyca/pyopenssl.git                                            python-security   pyopenssl"
  "https://github.com/pyca/bcrypt.git                                               python-security   bcrypt"
  "https://github.com/pyca/pynacl.git                                               python-security   pynacl"
  "https://github.com/jpadilla/pyjwt.git                                            python-security   pyjwt"
  "https://github.com/oauthlib/oauthlib.git                                         python-security   oauthlib"
  "https://github.com/requests/requests-oauthlib.git                                python-security   requests-oauthlib"
  "https://github.com/mpdavis/python-jose.git                                       python-security   python-jose"
  "https://github.com/mozilla/bleach.git                                             python-security   bleach"
  "https://github.com/scrapy/scrapy.git                                             python-security   scrapy-sec"

  # ── python-sast ─────────────────────────────────────────────────────────────
  "https://github.com/fportantier/vulpy.git                                         python-sast       vulpy"
  "https://github.com/adeyosemanputera/pygoat.git                                   python-sast       pygoat"
  "https://github.com/Contrast-Security-OSS/vulnpy.git                              python-sast       vulnpy"
  "https://github.com/erev0s/VAmPI.git                                              python-sast       vampi"
  "https://github.com/Checkmarx/Vulnerable-Web-Application.git                      python-sast       checkmarx-vuln-web"
  "https://github.com/stamparm/DVWA-Python.git                                      python-sast       dvwa-python"
  "https://github.com/righettod/poc-zip-slip.git                                    python-sast       poc-zip-slip"
  "https://github.com/we45/Vulnerable-Flask-App.git                                 python-sast       vulnerable-flask"
  "https://github.com/Securecodebox/django-DefectDojo.git                           python-sast       defectdojo"
  "https://github.com/DefectDojo/django-DefectDojo.git                              python-sast       defectdojo-main"
)
